Radio button style
neuralbertatech/natUI pull request #1
Opened 2023-02-13 21:57 UTC by yashmouje

Added Primary Color and Padding to Radio Buttons and their labels

2023-02-13 22:09 UTC, giancarlopernudisegura requested changes

2023-02-13 22:09 UTC, giancarlopernudisegura commented on sass/inputs.sass
> +  accent-color: #7967e1
Can you replace this with the `$primary` variable from [vars.sass](/neuralbertatech/natUI/blob/master/sass/vars.sass). This way if we change the value of the primary colour, the changes will take effect here.

2023-02-13 22:21 UTC, yashmouje commented on sass/inputs.sass
> +  accent-color: #7967e1
I have changed the color to `$primary`. You can have a look

2023-02-18 01:55 UTC, giancarlopernudisegura approved these changes
LGTM, good work!

2023-02-18 01:58 UTC, merged